const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
lucide.createIcons();

const state = { base: localStorage.getItem('apisaver_base') || 'https://api.apisaver.com/v1/chat/completions', key: localStorage.getItem('apisaver_key') || '', model: localStorage.getItem('apisaver_model') || 'gpt-4o-mini', lastResult: '' };
$('#apiBase').value = state.base; $('#apiKey').value = state.key; $('#apiModel').value = state.model; $('#modelBtn').childNodes[0].textContent = `${state.model} `;

function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2400); }
function openModal(id) { $(`#${id}`).classList.add('open'); }
function closeModal(id) { $(`#${id}`).classList.remove('open'); }
$$('[data-close]').forEach(b => b.addEventListener('click', () => closeModal(b.dataset.close)));
$('#openSettings').onclick = () => openModal('settingsModal');
$('#openSearch').onclick = () => { openModal('searchModal'); setTimeout(() => $('#searchInput').focus(), 80); };
$('#saveSettings').onclick = async () => { state.base = $('#apiBase').value.trim(); state.key = $('#apiKey').value.trim(); state.model = $('#apiModel').value.trim() || 'gpt-4o-mini'; localStorage.setItem('apisaver_base', state.base); localStorage.setItem('apisaver_key', state.key); localStorage.setItem('apisaver_model', state.model); $('#modelBtn').childNodes[0].textContent = `${state.model} `; $('#connectionStatus').textContent = state.key ? 'API Saver 已连接' : '本地工作区'; $('#testResult').textContent = state.key ? '配置已保存，下一次生成时将使用该接口。' : '已保存本地配置，可直接体验演示内容。'; toast('接口配置已保存'); };

let saveTimer; function persist() { clearTimeout(saveTimer); $('#saveStatus').textContent = '正在保存…'; saveTimer = setTimeout(() => { localStorage.setItem('manuscript', $('#manuscript').innerHTML); localStorage.setItem('chapterTitle', $('#chapterTitle').innerText); $('#saveStatus').textContent = '已自动保存'; }, 450); }
if (localStorage.getItem('manuscript')) $('#manuscript').innerHTML = localStorage.getItem('manuscript');
if (localStorage.getItem('chapterTitle')) $('#chapterTitle').innerText = localStorage.getItem('chapterTitle');
$('#manuscript').addEventListener('input', () => { const text = $('#manuscript').innerText; $('#wordCount').textContent = `${text.replace(/\s/g,'').length.toLocaleString()} / 8,000 字`; persist(); }); $('#chapterTitle').addEventListener('input', persist);

const demo = { continue: '楼梯尽头的人没有抬头，只将皮箱往前推了半寸。金属扣碰到水泥地，发出一声短促的回响。\n\n“你还是来了。”他说。\n\n沈砚握紧手电，光束落在那张被雨水泡得发白的脸上。那不是父亲，却戴着父亲的手表。', rewrite: '海风在凌晨三点转向。它穿过旧电台的天线，拨动每一根锈蚀的金属，像有人在黑暗里试着按下一段遗失的旋律。', expand: '可以从三个细节扩写：潮湿墙面上盐霜的纹理；沈砚认出母亲声音时喉结的停顿；闪电照亮楼梯尽头那双沾满海藻的鞋。让环境先于答案出现，保留悬念。', outline: '下一章《不存在的岛》\n1. 沈砚打开皮箱，发现一台仍在运转的录音机。\n2. 录音指向 1998 年的一次海底测绘，父亲并非唯一失踪者。\n3. “岛”只在退潮后的 17 分钟出现，沈砚必须在暴雨中出海。' };
const labels = { continue:'续写建议', rewrite:'表达改写', expand:'扩写建议', outline:'下一章大纲' };
async function generate(action, custom = '') { const output = $('#aiOutput'); output.innerHTML = '<div class="output-empty"><div class="output-icon"><i data-lucide="loader-circle"></i></div><strong>AI 正在构思…</strong><span>正在读取当前章节的语气与线索</span></div>'; lucide.createIcons(); const prompt = custom || ({continue:'请续写当前章节约 300 字，保持人物和悬念。',rewrite:'请改写当前选中的段落，让画面感更强。',expand:'请给出当前段落的扩写建议，补充环境与心理。',outline:'请基于当前章节生成下一章大纲，给出 3 个关键节点。'}[action] || '请协助我继续创作。'); const context = $('#manuscript').innerText.slice(-5000); let result = ''; if (state.key) { try { const res = await fetch(state.base, { method:'POST', headers:{'Content-Type':'application/json','Authorization':`Bearer ${state.key}`}, body:JSON.stringify({model:state.model,messages:[{role:'system',content:'你是中文小说编辑，保持原文风格，输出直接可用的创作内容。'},{role:'user',content:`${prompt}\n\n当前章节：\n${context}`}],temperature:.82}) }); const data = await res.json(); result = data.choices?.[0]?.message?.content || ''; if (!result) throw new Error('empty'); } catch (e) { result = demo[action] || demo.continue; toast('接口响应异常，已显示演示结果'); } } else result = demo[action] || '请先在设置中配置 API Key，或继续使用本地演示。'; state.lastResult = result; output.innerHTML = `<div class="eyebrow">${labels[action] || 'AI 建议'}</div><div class="ai-result">${result.replace(/</g,'&lt;')}</div><div class="result-actions"><button id="insertResult">插入正文</button><button id="copyResult">复制</button><button id="rerunResult">重新生成</button></div>`; $('#insertResult').onclick = () => { $('#manuscript').focus(); document.execCommand('insertText', false, `\n\n${result}`); persist(); toast('内容已插入正文'); }; $('#copyResult').onclick = async () => { await navigator.clipboard?.writeText(result); toast('已复制到剪贴板'); }; $('#rerunResult').onclick = () => generate(action, custom); }
$$('.prompt-card').forEach(card => card.addEventListener('click', () => generate(card.dataset.action)));
$('#sendPrompt').onclick = () => { const p = $('#promptInput').value.trim(); if (!p) return toast('先写下你想让 AI 做什么'); generate('custom', p); $('#promptInput').value = ''; }; $('#promptInput').addEventListener('keydown', e => { if (e.key === 'Enter' && e.shiftKey) { e.preventDefault(); $('#sendPrompt').click(); } });
$('#focusMode').onclick = () => { document.body.classList.toggle('focus-mode'); toast(document.body.classList.contains('focus-mode') ? '已进入专注模式' : '已退出专注模式'); }; $('#publishBtn').onclick = () => toast('章节已保存为待发布状态'); $('#clearContext').onclick = () => { $('#aiOutput').innerHTML = '<div class="output-empty"><div class="output-icon"><i data-lucide="sparkles"></i></div><strong>上下文已清除</strong><span>选择一个动作重新开始</span></div>'; lucide.createIcons(); toast('已清除本次 AI 上下文'); };
$('#newProject').onclick = $('#addProject').onclick = () => toast('新作品已创建，开始写下第一个场景吧'); $('#exportBtn').onclick = () => { const blob = new Blob([`${$('#chapterTitle').innerText}\n\n${$('#manuscript').innerText}`], {type:'text/plain;charset=utf-8'}); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = '潮声里的旧电台.txt'; a.click(); URL.revokeObjectURL(a.href); toast('章节已导出'); }; $('#togglePreview').onclick = () => { $('#manuscript').contentEditable = $('#manuscript').contentEditable === 'true' ? 'false' : 'true'; toast($('#manuscript').contentEditable === 'true' ? '已返回编辑模式' : '已切换预览模式'); };
$$('.tree-row').forEach(row => row.addEventListener('click', () => { $$('.tree-row').forEach(r => r.classList.remove('selected')); row.classList.add('selected'); toast(`已打开${row.querySelector('span').textContent}`); }));
